"""Static site generator: engine reference docs + a design/behaviour gallery.

This is the human-facing counterpart to the AI-agent-facing engine API —
it reuses the *exact same* introspection (``mudplot.capabilities()`` /
``mudplot.reference_markdown()``) and the *exact same* renderer, so the docs
and the pictures can never drift from what the engine actually does.

Needs ``mudplot[render]`` (numpy + matplotlib). The pure engine itself stays
dependency-free; only this dashboard-side generator pulls those in.

Usage
-----
    python -m dashboard.site --out dashboard/site_build
"""

from __future__ import annotations

from pathlib import Path

from .markdown_lite import markdown_to_html

__all__ = ["build_site"]

_PAGE = """<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>mudplot — reference & gallery</title>
<style>
  :root {{ color-scheme: light; }}
  body {{ font-family: -apple-system, "Segoe UI", Helvetica, Arial, sans-serif;
          max-width: 920px; margin: 2rem auto; padding: 0 1.25rem; color: #1a1a1a; }}
  h1 {{ font-size: 1.9rem; border-bottom: 3px solid #222; padding-bottom: .4rem; }}
  h2 {{ margin-top: 2.2rem; border-bottom: 1px solid #ddd; padding-bottom: .3rem; }}
  h3 {{ margin-top: 1.4rem; color: #333; }}
  nav {{ margin: 1rem 0 2rem; }}
  nav a {{ margin-right: 1rem; text-decoration: none; color: #0a5; font-weight: 600; }}
  code {{ background: #f2f2f2; padding: .1em .35em; border-radius: 4px;
          font-size: .92em; }}
  table {{ border-collapse: collapse; width: 100%; margin: .75rem 0 1.25rem; }}
  th, td {{ border: 1px solid #ddd; padding: .4rem .6rem; text-align: left;
            font-size: .92em; }}
  th {{ background: #fafafa; }}
  figure {{ margin: 1.5rem 0; text-align: center; }}
  figure img {{ max-width: 100%; border: 1px solid #eee; border-radius: 6px; }}
  figcaption {{ font-size: .88em; color: #555; margin-top: .4rem; }}
  .grid {{ display: grid; grid-template-columns: 1fr 1fr; gap: 1.2rem; }}
  footer {{ margin-top: 3rem; color: #888; font-size: .85em; }}
</style>
</head>
<body>
<nav>
  <a href="#gallery">Design gallery</a>
  <a href="#reference">Engine reference</a>
</nav>
<h1>mudplot</h1>
<p>Perceptually-uniform, colourblind-safe plotting for papers — engine reference
and a visual walkthrough of its design decisions, generated straight from the
library (never hand-written, never stale).</p>

<h2 id="gallery">Design gallery</h2>
{gallery}

<h2 id="reference">Engine reference</h2>
{reference}

<footer>Generated by <code>dashboard/site.py</code> from the live mudplot
engine — regenerate with <code>python -m dashboard.site</code>.</footer>
</body>
</html>
"""


def _figure_html(src: str, caption: str) -> str:
    return (
        f'<figure><img src="{src}" alt="{caption}">'
        f"<figcaption>{caption}</figcaption></figure>"
    )


def _generate_gallery_images(gallery_dir: Path) -> list[tuple[str, str]]:
    """Render the design-principle demo figures; returns (filename, caption)."""
    import matplotlib

    matplotlib.use("Agg")
    import mudplot as mp
    import numpy as np
    from mudplot.color import palette as P
    from mudplot.color.preview import preview

    gallery_dir.mkdir(parents=True, exist_ok=True)
    items: list[tuple[str, str]] = []

    # 1. Qualitative palette: CVD + greyscale safety
    import matplotlib.pyplot as plt

    fig, ax = plt.subplots(figsize=(6.5, 2.6))
    preview(P.qualitative(5), ax=ax)
    fig.tight_layout()
    fig.savefig(gallery_dir / "palette_safety.png", dpi=140)
    plt.close(fig)
    items.append(
        (
            "palette_safety.png",
            "Qualitative palette under normal vision, two CVD simulations, and "
            "true greyscale — equal-ish lightness + a small jitter keeps every "
            "swatch distinguishable in all four.",
        )
    )

    # 2. Redundant encoding: marker + dash + colour, shown in colour and grey
    rng = np.random.default_rng(0)
    x = np.linspace(0, 10, 60)
    data = {
        "x": list(x) * 3,
        "y": list(np.sin(x)) + list(np.sin(x) * 0.6) + list(np.sin(x) * 0.3),
        "g": ["A"] * 60 + ["B"] * 60 + ["C"] * 60,
    }
    p = (
        mp.plot(data)
        .line("x", "y", group="g")
        .legend(title="series")
        .labels(title="redundant encoding: colour + marker + dash")
    )
    p.save(str(gallery_dir / "redundant_encoding.png"))
    items.append(
        (
            "redundant_encoding.png",
            "Grouped series get a distinct marker and dash pattern in addition "
            "to colour, so comparisons survive greyscale print or colour-vision "
            "deficiency.",
        )
    )

    # 3. TeX WYSIWYG preview
    p2 = (
        mp.plot(data)
        .line("x", "y", group="g")
        .labels(x="t", y="signal")
        .legend(title="series")
    )
    fig3 = p2.preview(tex="ieee", caption="Figure 1. Example signal comparison.")
    fig3.savefig(gallery_dir / "tex_preview.png", dpi=140, bbox_inches="tight")
    plt.close(fig3)
    items.append(
        (
            "tex_preview.png",
            "TeX-aware preview: the figure is rendered at its true final size and "
            "font inside a mock IEEE column, so you see exactly what the paper "
            "will show.",
        )
    )

    # 4. Secondary axis + colour-mapped scatter + heatmap (render coverage)
    n = 40
    xs = np.linspace(0, 10, n)
    data2 = {
        "x": list(xs),
        "temp": list(20 + 5 * np.sin(xs)),
        "pressure": list(1000 + 40 * np.cos(xs * 0.5)),
        "val": list(rng.normal(size=n)),
    }
    p3 = (
        mp.plot(data2)
        .secondary_yaxis("Pressure (hPa)")
        .line("x", "temp", label="Temp")
        .line("x", "pressure", label="Pressure", axis="y2", color="#888888")
        .legend(location="outside right")
        .axes_style(spine_offset=6)
    )
    p3.save(str(gallery_dir / "secondary_axis.png"))
    items.append(
        (
            "secondary_axis.png",
            "Secondary y-axis, an outside-right legend, and offset ('despine') "
            "spines for a clean, Tufte-style look.",
        )
    )

    mat = (rng.normal(size=(18, 26)) + np.sin(np.linspace(0, 6, 26))).tolist()
    p4 = (
        mp.plot({})
        .matrix("m", mat)
        .heatmap("m", clabel="value", cmap_kind="diverging")
        .labels(title="LCH diverging heatmap")
    )
    p4.save(str(gallery_dir / "heatmap.png"))
    items.append(
        (
            "heatmap.png",
            "Heatmap and colour-mapped scatter use the same LCH sequential / "
            "diverging colormaps as the categorical palettes — perceptually "
            "uniform end to end.",
        )
    )

    return items


def build_site(out_dir: str = "dashboard/site_build") -> Path:
    """Generate the static docs+gallery site into ``out_dir``. Returns its path."""
    import mudplot as mp

    out = Path(out_dir)
    gallery_dir = out / "gallery"
    items = _generate_gallery_images(gallery_dir)

    gallery_html = (
        '<div class="grid">\n'
        + "\n".join(_figure_html(f"gallery/{name}", caption) for name, caption in items)
        + "\n</div>"
    )

    reference_html = markdown_to_html(mp.reference_markdown())

    page = _PAGE.format(gallery=gallery_html, reference=reference_html)
    (out / "index.html").write_text(page, encoding="utf-8")
    return out
